### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ArduinoFan0** [pschatzmann/arduino-SAM#2]
Which pin does the TTS output to on Leonardo/Micro?

**Comment by pschatzmann** [comment]
Your question does not make any sense: There is no output to any pin!
Maybe you try to read the Readme again!
Did you see the memory requirements ?

**Comment by ArduinoFan0** [comment]
It's a text to speech! it should output audio to a pin!

**Comment by ArduinoFan0** [comment]
Maybe it should output to an SD card.

**Comment by pschatzmann** [comment]
No, it generates a stream of PCM audio and you can do with it whatever you want. 
E.g. to output it using my [AudioTools](https://github.com/pschatzmann/arduino-audio-tools) library. But check the supported processors...

- [TTS Examples](https://github.com/pschatzmann/arduino-audio-tools/tree/main/examples/examples-tts)
